[project]
authors = ["Fuel Labs <contact@fuel.sh>", "Nazeeh Vahora"]
entry = "main.sw"
license = "Apache-2.0"
name = "counter-contract"

[dependencies]
asset = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.19.0" }

src20 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.3" }

src3 = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.3.3" }

